Repository elycruz/rollup-plugin-sass, pull requests merged in 2024-07, with the labels that each got.

#139 issue-132 - dedupe insertStyle in output files
  package.json
  src/index.ts
  src/insertStyle.ts
  src/style.ts
  test/fixtures/multiple-entry-points/entryA.js
  test/fixtures/multiple-entry-points/entryB.js
  test/index.test.ts
  test/snapshots/test/index.test.ts.md
  test/snapshots/test/index.test.ts.snap
  test/style.test.ts
  tsconfig.build.insertStyle.json
  tsconfig.build.plugin.json
Labels: enhancement, fix

#146 Issue #144,#145/commitlint
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.mjs
  package-lock.json
  package.json
  test/fixtures/insert/index2.js
  test/fixtures/insert/index2_sub-mod-1.js
  test/fixtures/insert/index2_sub-mod-2.js
  test/fixtures/insert/index3.js
  test/fixtures/insert/nested-style-1.scss
  test/fixtures/insert/nested-style-2.scss
  test/fixtures/insert/nested-styles.scss
Labels: enhancement, CI/CD

#147 feat: commitlint-and-husky - Adds commitlint pre-commit hook
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.mjs
  package-lock.json
  package.json
Labels: enhancement, CI/CD

#148 chore: move npm test to pre-push hook
  .husky/pre-push
Labels: enhancement
